[api_keys]
openai_key = "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"
tradingeconomics_key = "f506b2727f1f4ba:e6yphyhh1qr5or0"
newsdata_key = "pub_62009151ca9279302e0257edb988f5f5d93c2"